services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8765:9876" # host:container
    environment:
      - POSTGRES_DB=ghorkhoje
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ghorkhoje-network
    command: >
      bash -c "python ghorkhoje/manage.py runserver 0.0.0.0:8000"
  # python ghorkhoje/manage.py runserver 0.0.0.0:9876
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ghorkhoje
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "7654:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ghorkhoje-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    networks:
      - ghorkhoje-network

networks:
  ghorkhoje-network:
    driver: bridge

volumes:
  postgres_data:
