# Generated by Django 5.1.3 on 2026-07-29 11:11

import django.core.validators
import django.db.models.deletion
import utils.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='facility_icons/')),
                ('bill', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('area_name', models.CharField(max_length=255)),
                ('area_code', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=50, null=True)),
                ('house_name', models.CharField(blank=True, max_length=50, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('floor_number', models.CharField(blank=True, max_length=5, null=True)),
                ('rent_per_month', models.DecimalField(decimal_places=2, max_digits=15)),
                ('extra_bills', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('num_prepayment_months', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=15, max_digits=25)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=15, max_digits=25)),
                ('area_in_sqft', models.IntegerField(blank=True, null=True)),
                ('num_of_bedrooms', models.IntegerField(default=1)),
                ('num_of_bathrooms', models.IntegerField(default=1)),
                ('num_of_balconies', models.IntegerField(default=0)),
                ('num_of_kitchens', models.IntegerField(default=0)),
                ('num_of_living_rooms', models.IntegerField(default=0)),
                ('num_of_dining_rooms', models.IntegerField(default=0)),
                ('num_of_parking_spaces', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=1)),
                ('appointment_status', models.CharField(choices=[('APPOINTMENT_NON', 'No Appointment'), ('APPOINTMENT_CREATED', 'Appointment Created'), ('APPOINTMENT_ACCEPTED', 'Appointment Accepted'), ('APPOINTMENT_REJECTED', 'Appointment Rejected'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_COMPLETED', 'Appointment Completed')], default='APPOINTMENT_NON', max_length=50)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Archived')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='place.category')),
                ('facilities', models.ManyToManyField(blank=True, related_name='places', to='place.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=utils.functions.unique_image_path, validators=[utils.functions.validate_image_file, utils.functions.validate_image_size])),
                ('description', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('places', models.ManyToManyField(related_name='bookmarks', to='place.place')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description_match', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location_convenience', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_for_money', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('neighborhood', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='place.place')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Place Reviews',
                'db_table': 'place_reviews',
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='places_latitud_9cc1dc_idx'),
        ),
    ]
