# Generated by Django 5.1.3 on 2026-07-29 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('refunded', 'Refunded'), ('waiting_for_payment', 'Waiting for Payment'), ('payment_failed', 'Payment Failed')], default='pending', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('number_of_occupants', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('rent_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra_bills', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('num_prepayment_months', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=15, max_digits=25, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=15, max_digits=25, null=True)),
                ('area_in_sqft', models.IntegerField(blank=True, null=True)),
                ('agreed_to_terms', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='place.place')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
            },
        ),
    ]
