# Generated by Django 5.1.3 on 2026-07-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback Types',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('want_to_be_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.feedbacktype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.status')),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx'), models.Index(fields=['status'], name='feedback_fe_status__da51f2_idx'), models.Index(fields=['feedback_type'], name='feedback_fe_feedbac_8c1b98_idx')],
            },
        ),
    ]
